### ISSUE TITLE
Hosts values not prepulated when editing

### ISSUE THREAD

**Issue by JoshuaFolkerts** [andrewmarkham/contentsecuritypolicy#102]
I am not sure if this is just a specific version of 2.3.0.285 or after it was upgraged, but when editing a content security policy, the original value is not prepopulated when clicking on a policy to edit.  

To reproduce.  Add a host value to style-src, save it and then try to edit, it appears the other fields are populated with the original values you saved, but hosts are not.  
![Host-empty](https://github.com/user-attachments/assets/130088a0-97b0-4876-9d31-e3151d873b02)

**Comment by andrewmarkham** [comment]
@JoshuaFolkerts I will take a look
