### ISSUE TITLE
Cannot register issues

### ISSUE THREAD

**Issue by FridaWesterdahl** [andrewmarkham/contentsecuritypolicy#115]
Even though I see many CSP violations in the console, they are not being registered in the issues panel or dashboard. I can't find any errors when checking the logs, and I'm unsure if I'm missing some configuration or if something is wrong.

![image](https://github.com/user-attachments/assets/ca1d1729-2a52-4db4-9b75-78c1b10d7398)
![image](https://github.com/user-attachments/assets/85a14283-1ca0-4e0f-81b5-97a3c1af3bd4)
![image](https://github.com/user-attachments/assets/2f5f9264-756c-4543-bac4-195e3f4a4c77)

**Comment by andrewmarkham** [comment]
Hi @FridaWesterdahl 
Are you running this locally and testing in Chrome?  I found during development that Chrome will not return the errors to the reporting API when running under localhost.  Firefox works okay.

Andy

**Comment by FridaWesterdahl** [comment]
Hi!
Yes i did.  I have tried in Firefox and still does not have any reported issues displaying.
I don't know how I marked this issue as closed but the issue still remains :)

**Comment by andrewmarkham** [comment]
@FridaWesterdahl 

Can you share a screenshot of the settings screen, I want to see how you have configured the reporting

**Comment by FridaWesterdahl** [comment]
![image](https://github.com/user-attachments/assets/7b0286b8-5150-4d2a-a73c-2265b76cd095)

**Comment by andrewmarkham** [comment]
Hi @FridaWesterdahl,

Okay, this is a bit weird, can you 
1. share the response headers, I just want to check what has been created
2. snippet of the startup code where this is added and used
3. any configuration within the appSettings.

Thanks

**Comment by FridaWesterdahl** [comment]
Hi!
You were a lot faster than me! Thank you for your fast investigation and problem solving :)

**Comment by andrewmarkham** [comment]
Hi @FridaWesterdahl 

I have made a fix for this issue, please download the latest version V2.3.2.   FYI there is a bug with Firefox that's stopping the issues being reported.

https://bugzilla.mozilla.org/show_bug.cgi?id=1922967

Let me know if you see any more issues
