### ISSUE TITLE
Violation reported when nonce is set

### ISSUE THREAD

**Issue by blacktambourine** [andrewmarkham/contentsecuritypolicy#23]
Hi,

I'm seeing this error for an inline script tag

"Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' ''nonce-74e1441e-1985-44d1-8d57-676b6ca3273e''". Either the 'unsafe-inline' keyword, a hash ('sha256-nxUK0e7dsIKkkKXtZnnZ5fL3g1FSxV6g5v3Wi2aal4Y='), or a nonce ('nonce-...') is required to enable inline execution."

CSP Headers returned:

content-security-policy: script-src 'self' ''nonce-74e1441e-1985-44d1-8d57-676b6ca3273e'' ;  report-uri https://localhost:44361/api/csp/violations;  report-to https://localhost:44361/api/csp/violations;

Inline script tag:
 <script nonce="74e1441e-1985-44d1-8d57-676b6ca3273e">

**Comment by andrewmarkham** [comment]
Hi,

I can recreate this. I need to confirm but this looks to be caused by additional single quotes around the nonce property in the header.

I will confirm and get a fix out.

Andy

**Comment by andrewmarkham** [comment]
Hi,

This is now fixed, please take the latest version form the Optimizely feed.
