### ISSUE TITLE
404 on clientresources/csp-app.js on Linux DXP

### ISSUE THREAD

**Issue by blacktambourine** [andrewmarkham/contentsecuritypolicy#27]
I've deployed to a Linux instance on DXP, when trying to load the Security page I get a 404 on the "clientresources/csp-app.js".

**Comment by hybrid897** [comment]
Seems like case sensitivity is causing an issue when hosted on linux?

.../EPiServer/Jhoose.Security/clientresources/csp-app.js  - Not Found
.../EPiServer/Jhoose.Security/ClientResources/csp-app.js - Capitalization on ClientResources works

Running locally on windows both resolve.

**Comment by andrewmarkham** [comment]
I have been doing some research about this.  The underlying FileProvider uses the underlying OS, and Linux is case-sensitive. 

I will get a fix out for this over the next few days.

I think that this will catch a few people out.

**Comment by andrewmarkham** [comment]
A fix has been uploaded to the Optimizely nuget feed 1.1.2
