### ISSUE TITLE
JhooseSecurityInitilizationModule.cs setting global JSON Serializer properties

### ISSUE THREAD

**Issue by skfedm** [andrewmarkham/contentsecuritypolicy#52]
The initialization module is setting global JSON serializer settings and forcing camel case properties in JSON responses throughout any application which references Jhoose.

**Comment by andrewmarkham** [comment]
This is caused by the following sequence of code in the initialization module.

``` c#
                var formatters = GlobalConfiguration.Configuration.Formatters;
                var jsonFormatter = formatters.JsonFormatter;

                var enumConverter = new Newtonsoft.Json.Converters.StringEnumConverter();
                jsonFormatter.SerializerSettings.Converters.Add(enumConverter);
                
                jsonFormatter.SerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();
```
This code has been removed but may need to be added back into your main solution if there are serialization issues in other apis.

**Comment by andrewmarkham** [comment]
@skfedm A fix for this has been released.  See https://github.com/andrewmarkham/contentsecuritypolicy/releases/tag/V1.5.1
