### ISSUE TITLE
Host field in CSP allows invalid characters

### ISSUE THREAD

**Issue by adrianchandler** [andrewmarkham/contentsecuritypolicy#63]
This applies to latest version (1.4.0) and on Optimizely CMS 12 (12.13.2)

When entering text in the host field, invalid characters are not stripped out and this causes a 500 error on all pages of the webite - so effectively brings the site down.

Steps to repoduce:
1. On the "Security Page" in the CMS, edit any src field in the policy (e.g. frame-src)
2. In the edit overlay, enter "abc.com" followed by a carriage return, then enter "def.com" in the "Host Source" text box at the bottom of the form
3. Click "Ok" to save the entry

Now all pages throw a 500 error for invalid char in headers.
To remedy, you have to go into DB and manually edit row in tblBigTable to fix as changing it back via the UI doesn't work.

**Comment by andrewmarkham** [comment]
Hi @adrianchandler,

Thanks for letting me know, I will take a look into this issue

**Comment by andrewmarkham** [comment]
Hi @adrianchandler 

I have uploaded a new version #71 (V1.5.0), this should resolve the issue.  The module now strips out CRLF, further to this any errors are now logged and will not crash the solution.
