### ISSUE TITLE
Error adding headers if http request pipeline is re-run

### ISSUE THREAD

**Issue by adrianchandler** [andrewmarkham/contentsecuritypolicy#64]
This plugin seems to add headers without checking if they already exist. Therefore errors are thrown if the pipeline is rerun. In our solution we are using in startup.cs to redirect server side to custom error pages:

_app.UseStatusCodePagesWithReExecute("/statuscode/{0}");_

This causes this plugin to try to add the headers again but they are already there. 

There may be other scenarios where the headers might already be set by some other middleware so this plugin should set or add the headers rathen than try to add them without checking if they exist first.

**Comment by andrewmarkham** [comment]
Hi @adrianchandler 

I will investigate, thanks for reporting.

Andy

**Comment by andrewmarkham** [comment]
Duplicated by #65

**Comment by andrewmarkham** [comment]
Hi @adrianchandler 

Duplicate headers are now detected and will no longer be added.
