### ISSUE TITLE
Missing feature preload on StrictTransportSecurity

### ISSUE THREAD

**Issue by LucGosso** [andrewmarkham/contentsecuritypolicy#68]
Trying to improve my Optimizely Blog site and using this swedish service for security scaning. 
    
    https://webbkoll.dataskydd.net/en/results?url=http%3A%2F%2Foptimizely.blog
    
    
![image](https://user-images.githubusercontent.com/9716195/214107795-8a223da2-5527-481f-ba6f-30985191668a.png)

    
  Missing Preload eg: "Strict-Transport-Security: max-age=31536000; includeSubDomains; preload"
    
    Suggestion:
    "StrictTransportSecurity": {
      "MaxAge": 31536000,
      "IncludeSubDomains": true, 
      "preload":  true
    },
    
    Meanwhile, how do i disable StrictTransportSecurity from your plugin?

**Comment by LucGosso** [comment]
Meanwhile, how do i disable StrictTransportSecurity from your plugin? 

"Enabled": false, 

got it

**Comment by andrewmarkham** [comment]
Hi @LucGosso 

I take it from the comment above that you have worked out how to disable the StrictTransportSecurity header?

I have looked into the preload option, and reading the following information https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security it seems that this is not part of the specification.  Reading further it seems that Google also states that you should be careful about enabling this. https://hstspreload.org/

I need to think about this and consider if it is a valid option as it is not part of the standard, be good to get your thoughts.

If you do need this, then you can always add the header yourself.

Andy
