### ISSUE TITLE
navigation.bundle.js console error

### ISSUE THREAD

**Issue by smutekDamian** [andrewmarkham/contentsecuritypolicy#79]
Hi,

I've recently installed this package in the Optimizely 12 project, it is really great stuff. 

I am seeing a small bug in the admin dashboard, a console error regarding the navigation.bundle.js file.

![image](https://github.com/andrewmarkham/contentsecuritypolicy/assets/23149907/2650074e-428c-430a-813e-35d9bb168658)

It looks like Optimizely tries to fetch notifications but gets the 400 HTTP response. I've made a quick investigation and probably the @Html.AntiForgeryToken() is missing from JhooseSecurityAdmin/index.cshtml file. I've tried it locally and added a token next to     @Html.Raw(Html.CreatePlatformNavigationMenu()) line which seems to fix the issue.

![image](https://github.com/andrewmarkham/contentsecuritypolicy/assets/23149907/71ee9679-bf67-413f-85fc-55f23f07367b)

**Comment by andrewmarkham** [comment]
Hi @smutekDamian

Thanks for letting me know, I will take a look at getting a fix in for this.

**Comment by andrewmarkham** [comment]
Hi @smutekDamian 

This has been fixed in the latest release #86
