### ISSUE TITLE
Settings not displaying in UI

### ISSUE THREAD

**Issue by j3rbr0wn** [andrewmarkham/contentsecuritypolicy#80]
Hi Andy

Version: Jhoose.Security.Admin 1.5.2.235
None of the saved settings are populating in the UI when you hit the settings page directly (/EPiServer/Jhoose.Security/jhoosesecurityadmin#/csp/settings).
For example, the "mode" is defaulting to "on".  It appears to be displaying the initial state:
`settings: { mode: "on", reportingUrl: "" }`

Toggling between "Policy" and "Settings" in the nav displays the correct settings.

Cheers
Jeremy

**Comment by andrewmarkham** [comment]
@j3rbr0wn,  Cheers for letting me know 

Andy

**Comment by andrewmarkham** [comment]
Hi @j3rbr0wn 

The latest release #86 has changed the interface, this should rectify the problem.
