### ISSUE TITLE
Trouble with admin UI

### ISSUE THREAD

**Issue by FridaWesterdahl** [andrewmarkham/contentsecuritypolicy#82]
I'm getting alot of console errors from the Jhoose.Security scripts in the admin view, and it's displaying a blank page:
![image](https://github.com/andrewmarkham/contentsecuritypolicy/assets/91753428/2113a4a5-b914-4294-a890-2733e9fe33e9)
![image](https://github.com/andrewmarkham/contentsecuritypolicy/assets/91753428/e0fd1118-4156-4f2a-a1bb-88ff4c8421b7)
![image](https://github.com/andrewmarkham/contentsecuritypolicy/assets/91753428/bc77ae34-3c8d-4aa0-90e0-a8ceb50808b0)

I can see in the Network tab that the fetching from /EPiServer/Jhoose.Security/jhoosesecurityadmin and csp-app.js is OK and also the call to /api/csp and /api/csp/settings. But still something is clearly missing due to the errors. I'm using Episerver 12.17.1 and Jhoose.Security.Admin 1.5.2.235

**Comment by andrewmarkham** [comment]
Hi @FridaWesterdahl 

This isn't an error I would expect to see, can you also include the responses for the network requests in this ticket.  I am interested to see what it contains.

Thanks

**Comment by FridaWesterdahl** [comment]
![image](https://github.com/andrewmarkham/contentsecuritypolicy/assets/91753428/fb277bd9-4fb7-4aa4-b591-a8d5b29f119a)
![image](https://github.com/andrewmarkham/contentsecuritypolicy/assets/91753428/077204c7-11f0-41be-8e3a-169649b3bc70)
![image](https://github.com/andrewmarkham/contentsecuritypolicy/assets/91753428/5d546b9c-aa20-49a7-a49b-347497087102)
![image](https://github.com/andrewmarkham/contentsecuritypolicy/assets/91753428/70376e8c-a22d-48c5-8f8b-29348f09592e)

**Comment by andrewmarkham** [comment]
Hi @FridaWesterdahl 

I can see the problem, the JSON has been serialized incorrectly; the property names should be camelcase.  Either your application or one of your other modules has changed the default behaviour.

I will look at seeing how I can make sure the response is always consistent

**Comment by FridaWesterdahl** [comment]
Yes we solved it by serialize with camelcase. Thank you! Luc Gosso says hi by the way! :)

**Comment by andrewmarkham** [comment]
Hi @FridaWesterdahl, glad you got it fixed.  Good to hear from Luc, say hi back :)
